version: "3.9"

services:
  road_length:
    build: .
    volumes:
      - ./output:/app/output
    environment:
      INPUT_FILE: input/kelenfoldig.geojson
      OUTPUT_GEOJSON: output/sin_hossz.geojson
      OUTPUT_CSV: output/sin_hossza.csv